### ISSUE TITLE
QUESTION - Dynamically Generate Schemas to Union

### ISSUE THREAD

**Issue by devdazed** [fivetran/dbt_shopify#25]
**Are you a Fivetran customer?** 
Yes. Russ Bradberry, Thrasio

**Your Question**
How do we dynamically supply schema names to union.  We have hundreds of schemas and are adding new ones all the time, we can easily get the list of schemas we need by running the following SQL:
```sql
    SELECT LOWER(schema_name) AS schema_name
      FROM source_fivetran.information_schema.schemata
     WHERE schema_name ILIKE 'shopify_%'
```

So we would like to create a macro and somehow pass that list along without using the `vars` property in `dbt_project.yml`

**Additional context**
we tried creating a macro like the following:
```jinja
{% macro shopify_schemas(prefix='shopify_') %}

{% set shopify_schema_query %}
    SELECT LOWER(schema_name) AS schema_name
      FROM source_fivetran.information_schema.schemata
     WHERE schema_name ILIKE '{{ prefix }}%'
{% endset %}

{% set results = run_query(shopify_schema_query) %}

{% if execute %}
{%   set results_list = results.columns[0].values() %}
{% else %}
{%   set results_list = [] %}
{% endif %}

{{  log(results_list) }}
{{ return(results_list) }}

{% endmacro %}
```

and using it like:
```yaml
vars:
  shopify_database: source_fivetran
  union_schemas: "{{ shopify_schemas() }}"
```

but it seems that the yaml is interpreting the list as a string so wasn't able to make any progress this way.

**Please indicate the level of urgency and business impact of this request** 
While we can attempt to maintain a static list, it isn't scalable as the team doing the fivetran integrations is not the same as the team maintaining DBT so things may get lost, ideally we would be able to dynamically generate the list to avoid this requirement.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @devdazed thanks for opening this issue! I wanted to check in from my response in our [dbt slack](https://getdbt.slack.com/archives/C01D1R2JLLA/p1631815269089700) conversation.

I wonder if the reason the macro is not working is due to the compile of the query not being executed in time. I believe it may help if you are able to call that macro as a `on-run-start` config in order for it to populate your variables as a list and then use as the schema variable. 

Let me know how it goes!

**Comment by devdazed** [comment]
so it does run the query. the issue is that it returns a list and there doesn't seem to be a way to interpolate the list in the yml file as a list, it seems to be coerced into a string like: `'["a", "b", "c"]'` so the package ends up trying to iterate the string.  if the variable was a comma-delimited string then it would work fine, it just seems I can only bring in strings via jinja.  

is it possible to export a variable via `on-run-start` or from within the macro to be used in downstream packages? i couldn't find any way to set a `var` other than `dbt_project.yml` and command line

**Comment by fivetran-joemarkiewicz** [comment]
Ah I have actually come across this when dealing with our [dbt_salesforce_formula_utils](3762198478890) package. I may be able to leverage something over there for you to help parse out the string to be a true list. 

I'll take a closer look tomorrow. But in theory we should be able to convert this out of a string and to a true data format list.

**Comment by fivetran-joemarkiewicz** [comment]
@devdazed it may actually be best if you used the dbt-utils [get_column_values](https://github.com/dbt-labs/dbt-utils#get_column_values-source) macro instead of the select statement you have in your macro. The main reason being is because the get_column_values macro will return the list as an array that can be more easily parsed by our macro, instead of the string elements. 

Let me know if this helps!

**Comment by devdazed** [comment]
im getting the same result.  I think the issue is in the yaml, in order for it to parse we have to wrap it in double-quotes, which i suspect is what is coercing the list into a string.
```yaml
vars:
  shopify_database: source_fivetran
  union_schemas: "{{ shopify_schemas() }}"
```

because doing this throws an error:
```yaml
```yaml
vars:
  shopify_database: source_fivetran
  union_schemas: {{ shopify_schemas() }}
```

```
Running with dbt=0.20.2
Encountered an error:
Runtime Error
  Syntax error near line 31
  ------------------------------
  28 |
  29 | vars:
  30 |   shopify_database: source_fivetran
  31 |   union_schemas: {{ shopify_schemas() }}
  32 |
  33 |
  34 | # In this example config, we tell dbt to build all models in the example/ directory

  Raw Error:
  ------------------------------
  while constructing a mapping
    in "<unicode string>", line 31, column 18:
        union_schemas: {{ shopify_schemas() }}
                       ^
  found unhashable key
    in "<unicode string>", line 31, column 19:
        union_schemas: {{ shopify_schemas() }}
```

so it seems like maybe dbt doesn't parse the jinja in the yaml file before parsing the yaml and instead may be only parsing jija within string values in the yaml file.
```

**Comment by fivetran-joemarkiewicz** [comment]
@devdazed I have looked into this a bit more and running into some similar errors as you. I swear I have come across this issue and resolution before. I will keep digging here and there to see if I can come up with a good solution!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for catching that @devdazed! I just updated the branch to remove the erroneous parenthesis.

You are correct that currently the union ability is only available for the Shopify package. However, we have been increasingly been seeing requests that the union functionality is desired across packages. We have even seen users open PRs to add this functionality. See [here](https://github.com/fivetran/dbt_klaviyo_source/pull/8/files) for how a customer opened a PR to add the functionality in the Klaviyo package.

If you would like a similar functionality to be added in a future release of the Stripe package I would recommend opening a [feature request](https://github.com/fivetran/dbt_stripe/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=FEATURE+-+%5Byour+feature+request+title+here%5D) on the dbt_stripe package and our team will be able to scope it out for a future enhancement. Or we always welcome community contributions if you wanted to try and open a PR. Otherwise, once you open the feature request we can coordinate from there when our team will be able to address the request.

Finally, if the updates to the fivetran_utils package work I can go about pushing those changes to the next release.

**Comment by fivetran-joemarkiewicz** [comment]
@devdazed the `dbt_fivetran_utils` package has been updated and now includes the functionality described in this thread. Thank you for this great question and I hope the macro update helps going forward!
